### ISSUE TITLE
[Feature request] Allow the ability for the pinned tabs section to show as many pinned tabs have been configured

### ISSUE THREAD

**Issue by vraravam** [greeeen-dev/natsumi-browser#7]
I found this solution in the reddit forums.
I like the ability for the pinned tabs to show all the tabs in that section without being limited to 6 in number.
The relevant css in the `userChrome.css` is:
```css
/* Elongate the pinned tabs section */
#vertical-pinned-tabs-container {
  max-height: none !important;
}
```

Can you please incorporate this into natsumi-browser? BTW, this collection of tweaks is GREAT!!!!! It enhances Zen even further! I am using this for the past few days and I really appreciate your efforts in bringing us this collection in a easily followed installation procedure!
